# Generated by Django 5.0.3 on 2024-03-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_figurine_options_figurine_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figurine',
            name='have_it',
            field=models.BooleanField(default=False, verbose_name="Je l'ai"),
        ),
        migrations.AlterField(
            model_name='figurine',
            name='liked',
            field=models.PositiveIntegerField(default=0, verbose_name="J'aimes"),
        ),
        migrations.AlterField(
            model_name='figurine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Prix €'),
        ),
    ]
