# Generated by Django 5.0.3 on 2024-03-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_figurine_have_it_alter_figurine_liked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='figurine',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
